bacula-db-data:
  image: redcoolbeans/bacula-opensource-db-data:7.2.0
  # build: bacula-db-data
  container_name: bacula-db-data

bacula-db:
  image: redcoolbeans/bacula-opensource-db:7.2.0
  # build: bacula-db
  container_name: bacula-db
  hostname: bacula-db
  volumes_from:
    - bacula-db-data:rw
  environment:
    POSTGRES_PASSWORD: U8azIbKXY9QD

bacula-dir:
  image: redcoolbeans/bacula-opensource-dir:7.2.0
  # build: bacula-dir
  container_name: bacula-dir
  hostname: bacula-dir
  ports:
    - "9101:9101" # bconsole -> dir
    - "9102:9102" # dir -> fd
  extra_hosts:
    - "bacula-fd:127.0.0.1"
  volumes:
    - ./configs/ssl:/opt/bacula/etc/ssl:ro
    - ./configs/dir:/opt/bacula/etc:ro
  environment:
    DB_NAME: bacula
    DB_HOST: bacula-db
    DB_USER: postgres
    DB_PASSWORD: U8azIbKXY9QD
    BACULA_DEBUG: 100

bacula-sd:
  image: redcoolbeans/bacula-opensource-sd:7.2.0
  # build: bacula-sd
  container_name: bacula-sd
  hostname: bacula-sd
  ports:
    - "9103:9103" # dir/fd -> sd
  volumes:
    - ./configs/sd:/opt/bacula/etc:ro
    - ./configs/ssl:/opt/bacula/etc/ssl:ro
    - ./backups:/b:rw
  environment:
    BACULA_DEBUG: 100
